version: '3.9'

services:
  web:
    build: .
    command: bash -c "source /myprojects/alienv/bin/activate && python manage.py collectstatic --noinput && gunicorn qr_code_generate.wsgi:application  --bind 0.0.0.0:8000"
    restart: always
    image: djangoindocker
    container_name: murad
    volumes:
      - static_volume:/myprojects/static/
      - media_volume:/myprojects/media/
    ports:
      - "8000:8000"
    networks:
      - custom-net
  nginx:
    build: ./nginx
    restart: always
    volumes:
      #- nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/myprojects/static/
      - media_volume:/myprojects/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - custom-net


      
networks:
  custom-net:
    external: true

volumes:
 static_volume:
 media_volume: